#!/usr/bin/env node
/*
 * One-command version bump.
 *
 * Writes the new version into the workspace Cargo.toml (the canonical
 * source) and then defers to sync-version.mjs to propagate it to
 * apps/desktop/package.json + apps/desktop/src-tauri/tauri.conf.json.
 *
 * Sub-crates (apps/desktop/src-tauri, crates/lunalib, crates/psarc) all
 * declare `version.workspace = true` so they pick up the new version
 * automatically from the workspace table — no per-crate edit needed.
 * `Cargo.lock` is regenerated by `cargo build` on the next compile;
 * we don't touch it here so people can run this script without a
 * full Cargo toolchain in PATH.
 *
 * Usage:
 *   node scripts/bump-version.mjs 0.1.2
 *   bun  scripts/bump-version.mjs 0.6.0
 *   bun  scripts/bump-version.mjs 0.6.0 --dry-run
 *
 * Flags:
 *   --dry-run   Show the OLD → NEW transition and exit without writing.
 *
 * After this script runs, three files in the working tree will have
 * the new version. Commit them together as part of the release PR.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const newVersion = args.find((a) => !a.startsWith("--"));

if (!newVersion) {
  console.error("Usage: node scripts/bump-version.mjs <version> [--dry-run]");
  console.error("Example: node scripts/bump-version.mjs 0.1.2");
  process.exit(1);
}

// Sanity-check the format. Tauri / Cargo / npm all expect a SemVer
// triple (optionally with a pre-release suffix). Catching this here
// is friendlier than failing in three different parsers later.
if (!/^\d+\.\d+\.\d+(-[A-Za-z0-9.-]+)?$/.test(newVersion)) {
  console.error(
    `[bump-version] "${newVersion}" doesn't look like a valid SemVer string`,
  );
  console.error("Expected: MAJOR.MINOR.PATCH or MAJOR.MINOR.PATCH-prerelease");
  process.exit(1);
}

// --- Read the current workspace version so we can print OLD → NEW
// and short-circuit when there's nothing to do. ---
const cargoPath = resolve(repoRoot, "Cargo.toml");
const cargoText = readFileSync(cargoPath, "utf-8");
const currentMatch = cargoText.match(
  /\[workspace\.package\][\s\S]*?\nversion\s*=\s*"([^"]+)"/m,
);
if (!currentMatch) {
  console.error(
    `[bump-version] failed to locate workspace.package.version in ${cargoPath}`,
  );
  process.exit(1);
}
const currentVersion = currentMatch[1];

if (currentVersion === newVersion) {
  // Idempotency — running the same bump twice (e.g. CI retry, or a
  // human re-running after a revert) should succeed silently instead of
  // pretending it did work. We still defer to the sync script so any
  // drift between Cargo.toml and the JSON files gets healed.
  console.log(
    `[bump-version] already at ${newVersion} — nothing to write. Running sync to heal any drift…`,
  );
  if (dryRun) {
    console.log("[bump-version] (--dry-run) skipping sync");
    process.exit(0);
  }
  const syncResult = spawnSync(
    process.execPath,
    [resolve(here, "sync-version.mjs")],
    { stdio: "inherit" },
  );
  process.exit(syncResult.status ?? 0);
}

console.log(`[bump-version] ${currentVersion} → ${newVersion}`);

if (dryRun) {
  console.log("[bump-version] (--dry-run) no files written");
  console.log("[bump-version] would update:");
  console.log("  Cargo.toml                                  (workspace)");
  console.log("  apps/desktop/package.json                   (via sync-version)");
  console.log("  apps/desktop/src-tauri/tauri.conf.json      (via sync-version)");
  console.log("[bump-version] sub-crates inherit via version.workspace = true");
  process.exit(0);
}

// --- Update Cargo.toml workspace.package.version in place ---
const updated = cargoText.replace(
  /(\[workspace\.package\][\s\S]*?\nversion\s*=\s*")[^"]+(")/m,
  `$1${newVersion}$2`,
);
if (updated === cargoText) {
  console.error(
    `[bump-version] failed to rewrite workspace.package.version in ${cargoPath}`,
  );
  process.exit(1);
}
writeFileSync(cargoPath, updated);
console.log(`[bump-version] Cargo.toml → ${newVersion}`);

// --- Defer to the sync script for the other two files ---
const result = spawnSync(
  process.execPath,
  [resolve(here, "sync-version.mjs")],
  { stdio: "inherit" },
);
process.exit(result.status ?? 0);
